name: base
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pip:
      - fastapi==0.115.0
      - uvicorn==0.30.6
      - SQLAlchemy==2.0.34
      - pydantic==2.8.2
      - pydantic-settings==2.5.2
      - python-multipart==0.0.9
      - email-validator==2.2.0
      - passlib[bcrypt]==1.7.4
      - alembic==1.13.2
      - PyJWT==2.9.0
      - psycopg[binary]==3.2.1
